In [ ]:
import yfinance as yf

# 비트코인 가격 데이터 다운로드 (5년치 데이터)
btc = yf.download('BTC-USD', period='5y', interval='1d')

# 데이터 확인
print(btc.head())

[*********************100%***********************]  1 of 1 completed

Price             Close         High          Low         Open       Volume
Ticker          BTC-USD      BTC-USD      BTC-USD      BTC-USD      BTC-USD
Date
2020-03-05  9078.762695  9142.054688  8757.253906  8760.285156  39698054597
2020-03-06  9122.545898  9167.695312  9032.079102  9078.308594  40826885651
2020-03-07  8909.954102  9163.220703  8890.744141  9121.600586  36216930370
2020-03-08  8108.116211  8914.343750  8105.252930  8908.206055  39973102121
2020-03-09  7923.644531  8177.793457  7690.098145  8111.146484  46936995808

In [40]:
# 멀티인덱스에서 'Ticker' 레벨을 드롭하고, 컬럼명을 설정
btc.columns = ['Close', 'High', 'Low', 'Open', 'Volume']

# 인덱스를 리셋하고 'Date' 컬럼을 추가
btc = btc.reset_index()

# 'Date', 'Close', 'High', 'Low', 'Open', 'Volume' 순서로 컬럼 재정렬
btc = btc[['Date', 'Close', 'High', 'Low', 'Open', 'Volume']]

In [41]:
btc

,Date,Close,High,Low,Open,Volume
0,2020-03-05,9078.762695,9142.054688,8757.253906,8760.285156,39698054597
1,2020-03-06,9122.545898,9167.695312,9032.079102,9078.308594,40826885651
2,2020-03-07,8909.954102,9163.220703,8890.744141,9121.600586,36216930370
3,2020-03-08,8108.116211,8914.343750,8105.252930,8908.206055,39973102121
4,2020-03-09,7923.644531,8177.793457,7690.098145,8111.146484,46936995808
...,...,...,...,...,...,...
1822,2025-03-01,86031.914062,86522.304688,83794.234375,84373.867188,29190628396
1823,2025-03-02,94248.351562,95043.437500,85040.210938,86036.257812,58398341092
1824,2025-03-03,86065.671875,94429.750000,85081.304688,94248.421875,70072228536
1825,2025-03-04,87222.195312,88911.273438,81529.242188,86064.070312,68095241474
1826,2025-03-05,87401.210938,87735.914062,86466.078125,87236.250000,59492311040